version: "2"
services:
  backend:
    build: .
    network_mode: host
    command: bash -c "
      python3 -u backend/manage.py runserver 0.0.0.0:8080"
    depends_on: [database]
  database:
    container_name: database
    build: ./database
    network_mode: host
