# Generated by Django 3.0 on 2020-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0004_auto_20191213_1842'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE lakes_lake ALTER COLUMN perimeter TYPE geometry(MULTIPOLYGON,4326) USING ST_FlipCoordinates(perimeter)::geometry(MULTIPOLYGON,4326);",
            "ALTER TABLE lakes_lake ALTER COLUMN perimeter TYPE geometry(MULTIPOLYGON,4326) USING ST_FlipCoordinates(perimeter)::geometry(MULTIPOLYGON,4326);"
        )
    ]
