# Generated by Django 3.0 on 2019-12-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lake',
            old_name='descriptio',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lake',
            old_name='geom',
            new_name='perimeter',
        ),
    ]
