# Generated by Django 3.0 on 2019-12-10 23:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0002_auto_20191210_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', models.FloatField()),
                ('cont_id', models.IntegerField()),
                ('calc_dep_m', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lakes.Lake')),
            ],
        ),
    ]
