# Generated by Django 3.0 on 2019-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0003_contour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lake',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='lake',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
