# Generated by Django 3.0 on 2020-01-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0005_switch_lat_lon_lakes'),
    ]

    operations = [
    migrations.RunSQL(
        "ALTER TABLE lakes_contour ALTER COLUMN geom TYPE geometry(MULTILINESTRING,4326) USING ST_FlipCoordinates(geom)::geometry(MULTILINESTRING,4326);",
        "ALTER TABLE lakes_contour ALTER COLUMN geom TYPE geometry(MULTILINESTRING,4326) USING ST_FlipCoordinates(geom)::geometry(MULTILINESTRING,4326);"
    )
    ]
